/**
 * Issuetracker - OpenAPI 3.0.3
 * Some useful links: - [The Issuetracker repository](https://github.com/swagger-api/swagger-projectstore) - [The source API definition for the projects service](https://github.com/dnowak94/issuetracker/blob/master/backend/openapi.yaml)
 *
 * OpenAPI spec version: 1.0.11
 * Contact: dnowak94@live.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Issue } from './issue';
import { Task } from './task';

export interface Project { 
    id?: number;
    name: string;
    description: string;
    issues?: Array<Issue>;
    tasks?: Array<Task>;
}