/**
 * Issuetracker - OpenAPI 3.0.3
 * Some useful links: - [The Issuetracker repository](https://github.com/swagger-api/swagger-projectstore) - [The source API definition for the projects service](https://github.com/dnowak94/issuetracker/blob/master/backend/openapi.yaml)
 *
 * OpenAPI spec version: 1.0.11
 * Contact: dnowak94@live.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type TaskStatus = 'todo' | 'work_in_progress' | 'done';

export const TaskStatus = {
    Todo: 'todo' as TaskStatus,
    WorkInProgress: 'work_in_progress' as TaskStatus,
    Done: 'done' as TaskStatus
};