services:
  db:
    image: mysql:8.2.0-oraclelinux8
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_USER=issuetracker
      - MYSQL_PASSWORD=issuetracker
      - MYSQL_DATABASE=issuetracker
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./data/mysql:/var/lib/mysql"
    ports:
      - "3306:3306"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
  front-envoy:
    build:
      context: ./envoy
    environment:
      - ENVOY_CONFIG="./envoy-issuetracker.yaml"
    depends_on:
      issues-envoy:
        condition: service_healthy
    ports:
    - "${PORT_PROXY:-8080}:8080"
    - "${PORT_HTTPS:-8443}:8443"
    - "${PORT_STATS:-8001}:8001"
  issues-envoy:
    build:
      context: ./envoy
      target: envoy-admin
      args:
        ENVOY_CONFIG: ./issues-envoy.yaml
        ENVOY_ADMIN_PORT: 8001
    depends_on:
      issues:
        condition: service_healthy
  issues:
    image: issuetracker-issue-service
    environment:
      - SERVICE_NAME=issues