services:
  issues:
    image: issuetracker_issue_service
    environment:
      - SERVICE_NAME=issues
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=issuetracker
      - DB_NAME=issuetracker
      - DB_PASSWORD=password
    ports:
      - "8080:8080"
    networks:
      - jenkins
  db:
    image: postgres:16.1-alpine3.19
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=issuetracker
      - POSTGRES_DB=issuetracker
      - PGPASSWORD=password
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks:
      - jenkins
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - jenkins
networks:
  jenkins:
    external: true