#!/usr/bin/env groovy
pipeline {
    agent any
    options {
        checkoutToSubdirectory('backend/issuetracker')
    }
    stages {
        stage('build') {
            steps {
                sh 'mvn -DskipTests clean package'
            }
        }
    }
}