#!/usr/bin/env groovy
pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                sh 'mvn -f backend/issuetracker/pom.xml -DskipTests clean package'
            }
        }
    }
}