#!/usr/bin/env groovy
pipeline {
    agent any
    environment {
        DB_HOST = 'localhost'
        DB_PORT = 3306
    }
    stages {
        stage('Build') {
            steps {
                dir ('backend/issuetracker') {
                    sh 'mvn -DskipTests clean package'
                }
            }
        }
        stage('Test') {
            steps {
                dir ('backend/issuetracker') {
                    sh 'mvn test'
                }
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
    }
}