#!/usr/bin/env groovy
pipeline {
    agent any
    environment {
        DB_HOST = 'localhost'
        DB_PORT = 3306
    }
    stages {
        stage('SonarQube analysis') {
            withSonarQubeEnv(installationName: 'sonarqube-local') {
                sh 'mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.11.0.3922:sonar'
            }
        }
        stage('Build') {
            steps {
                dir ('backend/issuetracker') {
                    sh 'mvn -DskipTests clean package'
                }
            }
        }
        stage('Test') {
            steps {
                dir ('backend/issuetracker') {
                    sh 'mvn test'
                }
            }
            post {
                always {
                    junit 'backend/issuetracker/target/surefire-reports/*.xml'
                }
            }
        }
    }
}